name: Azure Dev Environment

on:
  push:
    branches:
      - 'feature/**'
      - 'dev'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Dev
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install and Build
        run: |
          cd wisebox-frontend
          npm install
          npm run build
        env:
          REACT_APP_API_BASE_URL: https://wisebox-api-dev-bth7b5fyc7ewamcr.northeurope-01.azurewebsites.net/api

      - name: Deploy to Azure Dev
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_DEV_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/wisebox-frontend/build"
          api_location: ""
          output_location: ""
          skip_app_build: true
